language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm@2 bower jshint
  - npm cache clean
  - npm install
  - bower cache clean
  - bower install
before_script:
  - jshint .
