language: node_js
node_js:
  - '0.10'
install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm@2
  - npm install -g bower
  - npm cache clean
  - npm install
  - bower install
